#+AUTHOR: lambdart
#+EMAIL: lambdart@protonmail.com
#+KEYWORDS: programming language exercises practice
#+LANGUAGE: en
#+PROPERTY: header-args :tangle no

* Reference

  - https://www.hackerrank.com/challenges/fp-array-of-n-elements/problem

* Problem
  Create an array of  integers, where the value of  is passed as an
  argument to the pre-filled function in your editor. This challenge
  uses a custom checker, so you can create any array of  integers. For
  example, if , you could return , , or any other array of equal length.

  Note: Code stubs are provided for almost every language in which you
  must either fill in a blank (i.e., ____) or write your code in the
  area specified by comments.

  *Input Format*

  A single integer, *n*.

  *Output Format*

  The function must return an array, list, or vector of *N* integers.
  Stub code in the editor prints this to stdout as a space, comma, or
  semicolon-separated list (depending on your submission language).

  [Note]: Your output need not match the Expected Output exactly; the
  size of your printed list is confirmed by a custom checker, which
  determines whether or not you passed each test case.

* Constrains

  * 1 <= N <= 100

* Samples
** Input

   #+BEGIN_SRC
   10
   #+END_SRC

** Output

   #+BEGIN_SRC
   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
   #+END_SRC

* Method Signature

  - Number Of Parameters: 1
  - Parameters: [n]
  - Returns: List or Vector
