#+AUTHOR: lambdart
#+EMAIL: lambdart@protonmail.com
#+KEYWORDS: programming language exercises practice
#+LANGUAGE: en
#+PROPERTY: header-args :tangle no

* Reference

  - https://www.hackerrank.com/challenges/fp-filter-array/problem

* Problem

  Filter a given array of integers and output only those values that
  are less than a specified value . The output integers should be in
  the same sequence as they were in the input. You need to write a
  function with the recommended method signature for the languages
  mentioned below. For the rest of the languages, you have to write a
  complete code.

  *Input Format*

  The first line contains the delimiter .
  The next  lines each contain an integer, which represents the elements
  of the list/array. You have to read the input to the End-Of-File.

  *Output Format*

  Print all the integers from the array that are less than the given
  upper limit  in value on separate lines. The sequence should be the
  same as it was in the original array.

* Constrains

  1. 0 <= B <= 100
  2. For any element, *Y* in the array:
     * 100 <= Y <= 100
     * -100 <= X <= 100

* Samples
** Input

   #+BEGIN_SRC
   3
   10
   9
   8
   2
   7
   5
   1
   3
   0
   #+END_SRC

** Output

   #+BEGIN_SRC
   2
   1
   0
   #+END_SRC

* Recommended Method Signature

  - Number Of Parameters: 2
  - Parameters: [upper-limit(X) list]
  - Returns: List or Vector
